#!/bin/bash
# install - installs and configure machine automatically

# Install git
    yes | sudo apt install git

# Install fzf
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    yes | ~/.fzf/install

# Install vim
    yes | sudo apt install vim

# Install ranger
    yes | sudo apt install ranger

# Copy ranger configs
    ranger --copy-config=all

# Install cmus
    yes | sudo apt install cmus

# Install git
    yes | sudo apt install git

# Install neofetch
    yes | sudo apt install neofetch

# Install python and pip
    yes | sudo apt install python
    yes | sudo apt install python-pip
    sudo -H pip install --upgrade setuptools

# Install python3 and pip3
    yes | sudo apt install python3
    yes | sudo apt install python3-pip
    sudo -H pip3 install --upgrade setuptools

# Install powerline-shell
    pip install powerline-shell

# Dependencies
    yes | sudo apt install libjpeg-dev
    yes | sudo apt install zlib1g-dev
    yes | sudo apt install libxtst-dev

# Install ueberzug
    sudo pip3 install ueberzug

# Install mpv
    yes | sudo apt install mpv

# Install vlc
    yes | sudo apt install vlc

# Install feh
    yes | sudo apt install feh

# Install pywal
    pip3 install pywal

# Install imagemagick
    yes | sudo apt install imagemagick

# Install zathura
    yes | sudo apt install zathura

# Install and configure sdcv
    yes | sudo apt install wget
    yes | sudo apt install sdcv
    wget https://web.archive.org/web/20140428003644/http://abloz.com/huzheng/stardict-dic/dict.org/stardict-dictd_www.dict.org_gcide-2.4.2.tar.bz2
    sudo mkdir -p /usr/share/stardict/dic/
    sudo tar -xvjf  stardict-dictd_www.dict.org_gcide-2.4.2.tar.bz2 -C /usr/share/stardict/dic
    rm stardict-dictd_www.dict.org_gcide-2.4.2.tar.bz2

# Dotfiles
    cd /tmp
    git clone https://github.com/ddmin/Dotfiles.git
    cd Dotfiles
    cd dotfiles
    ./setup.sh
