* Frequently Encountered Problems
** 0. Linux
*** (0.0) General
**** (0.0.1) [[https://askubuntu.com/a/604302][Resize LVM Physical Volume]]

Check the file system
#+begin_example bash
sudo e2fsck -f /dev/mapper/<LOGICAL VOLUME>
#+end_example

Rearrange unallocated space at the end of the LVM.
#+begin_example bash
sudo pvs -v --segments /dev/<PHYSICAL VOLUME>
#+end_example

Remove external fragmentation.
#+begin_example bash
sudo pvmove --alloc anywhere /dev/<PHYSICAL VOLUME>:YYY-ZZZ
#+end_example

Where =YYY-ZZZ= is the block after =free= space.

Use =gparted= or =blivet-gui= to do the other heavy lifting.

**** (0.0.2) [[https://stackoverflow.com/a/17110941][Use tar to create gzip using multiple cores]]

#+begin_example
tar -c --use-compress-program=pigz -f <DIRECTORY>{.tar.gz,}
#+end_example
**** (0.0.3) Map Control-Backspace to Delete Word Terminal

=.inputrc=
#+begin_example bash
"\C-h": backward-kill-word
#+end_example

The Control-Backspace mapping (~\C-h~) can be found by pressing *Control-V* and then *Control-Backspace* in the terminal.

If that doesn't work for whatever reason:

=.bashrc=
#+begin_example bash
stty werase ^H
#+end_example

*** (0.1) Ubuntu
**** (0.1.1) ~Skipping acquire of ... doesn't support architecture 'i386'~

=/etc/apt/sources.list.d/<PACKAGE NAME>.list=

#+begin_example
deb [arch=amd64] https://.../ stable main
#+end_example

If options are already options specified, prepend it and separate it with a space.

#+begin_example
deb [arch=amd64 signed-by=...] https://.../ stable main
#+end_example

** 1. Ranger
*** (1.1) Ranger returns an error code

I aliased ranger to 'ranger && wal'. Probably has something to do with
wal

*** (1.2) Navigate to last directory in Ranger

#+BEGIN_EXAMPLE
  alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
#+END_EXAMPLE

*** (1.3) Change wallpaper in XFCE using ranger?

1. Run in Terminal: =xfconf-query -c xfce4-desktop -m= and change background.
2. =map bg shell wal --vte -q -i %f && xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitoreDP1/workspace0/last-image -s %d/%f=
** 2. Proton VPN
*** (2.1) [[https://askubuntu.com/questions/1319033/internet-stops-working-after-installing-protonvpn][ProtonVPN killswitch disables internet]]

#+BEGIN_EXAMPLE
  nmcli device
  sudo nmcli connection delete pvpn-killswitch
  sudo nmcli connection delete pvpn-ipv6leak-protection
#+END_EXAMPLE

*** (2.2) [[https://bbs.archlinux.org/viewtopic.php?id=270089][Proton VPN asks for password]]

(this might solve it, idk)

**** Add two lines to /etc/pam.d
#+BEGIN_EXAMPLE
  auth       optional     pam_gnome_keyring.so
  session    optional     pam_gnome_keyring.so auto_start
#+END_EXAMPLE

** 3. Firefox
*** (3.1) Firefox backspace to go back a page

=about:config=

=browser.backspace_action = 0=

*** (3.2) [[https://superuser.com/questions/1151161/enable-touch-scrolling-in-firefox][Firefox Touch Scrolling]]

=/etc/security/pam_env.conf=

#+BEGIN_EXAMPLE
   MOZ_USE_XINPUT2 DEFAULT=1
#+END_EXAMPLE

*** (3.3) [[https://www.reddit.com/r/firefox/comments/129w85w/is_there_a_way_to_disable_firefox_alt_keyboard/][Disable alt key to open menu]]

=about:config=

#+BEGIN_EXAMPLE
  ui.key.menuAccessKey            0
  ui.key.menuAccessKeyFocuses     false
#+END_EXAMPLE

*** (3.4) [[https://support.mozilla.org/en-US/questions/963501][Disable WebRTC in Firefox]]

=about:config=

#+BEGIN_EXAMPLE
  media.peerconnection.enabled        false
  media.navigator.enabled             false
#+END_EXAMPLE

*** (3.5) [[https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contextualIdentities][Firefox Contextual Identities]]

=about:config=

#+BEGIN_EXAMPLE
  privacy.userContext.enabled                                     true
  privacy.userContext.newTabContainerOnLeftClick.enabled          true
  privacy.userContext.ui.enabled          true
#+END_EXAMPLE

*** (3.6) [[https://superuser.com/questions/363827/how-can-i-disable-add-application-for-mailto-links-bar-in-firefox][Dismiss "Add ... as an application for mailto links?"]]

=about:config=

#+BEGIN_EXAMPLE
  network.protocol-handler.external.mailto              false
#+END_EXAMPLE

**** Related settings

#+BEGIN_EXAMPLE
  network.protocol-handler.expose.mailto                false
  network.protocol-handler.warn-external.mailto         false
#+END_EXAMPLE

*** (3.7) [[https://leochavez.org/index.php/2023/03/06/make-firefoxs-tabs-smaller/][Make Firefox bar thinner]]

=about:config=
#+begin_example
  browser.uidensity             1
#+end_example

** 3½ LibreWolf
*** (3½.1) [[https://github.com/aclap-dev/vdhcoapp/issues/205][Use VideoDownloadHelper]]

#+begin_example
mkdir -p ~/.librewolf/native-messaging-hosts/
cp ~/.mozilla/native-messaging-hosts/net.downloadhelper.coapp.json ~/.librewolf/native-messaging-hosts/
#+end_example

** 4. (Doom) Emacs
*** (4.1) Running emacs as a daemon

Start daemon

#+BEGIN_EXAMPLE
  /usr/bin/emacs --daemon
#+END_EXAMPLE

Open emacsclient

#+BEGIN_EXAMPLE
  emacsclient -c -a 'emacs'
#+END_EXAMPLE

*** (4.2) [[https://discourse.doomemacs.org/t/how-to-re-bind-keys/56][Keyboard mapping doesn't work (Doom)]]
**** (4.2.1) Major/Minor Mode overrides keybinding

#+BEGIN_SRC lisp
  (after! mode
      (keybinding))
#+END_SRC

**** (4.2.2) [[https://discourse.doomemacs.org/t/how-to-bind-keys-with-higher-precedence-than-evil-keybindings/3743/2][Evil Mode overrides keybinding]]

#+BEGIN_SRC lisp
  (map! :nvi "<KEY>" #'<KEYBINDING>)
#+END_SRC

#+BEGIN_EXAMPLE
      :n  normal
      :v  visual
      :i  insert
      :e  emacs
      :o  operator
      :m  motion
      :r  replace
      :g  global
#+END_EXAMPLE

**** (4.2.3) [[https://github.com/doomemacs/doomemacs/issues/6246][Can't add words to personal dictionary]]

Check value of =ispell-personal-dictionary= and ~touch~ the file.

#+begin_example
touch $HOME/.config/emacs/.local/etc/ispell/en.pws
#+end_example

** 5. Virtual Machines
*** (5.1) [[https://unix.stackexchange.com/questions/109117/virt-manager-copy-paste-functionality-to-the-vm/435665#435665][QEMU Virt-Manager Shared Clipboard]]
**** Ubuntu Virtual Machine: in the guest machine install:

#+BEGIN_EXAMPLE
  sudo apt install spice-vdagent
#+END_EXAMPLE

*** (5.2) [[https://blog.sergeantbiggs.net/posts/file-sharing-with-qemu-and-virt-manager/][Shared folders between guest and host]]

1. Click =Add Hardware= in virt-manager
2. =Filesystem= add =virtiofs=
3. In guest machine run:
   =sudo mount -t virtiofs <TARGET PATH> <MOUNT PATH>=

4. Automount Folder

   Add the line to ~/etc/fstab~

   =<TARGET PATH>       <MOUNT PATH>    virtiofs (or 9p)     defaults        0       0=

*** (5.3) [[https://github.com/virtio-win/virtio-win-pkg-scripts][Can't resize Windows Virtual Machine]]

Install
=virtio-win=
drivers on the Windows guest machine.
** ∞. Windows
*** (∞.1) No internet in the installer
Install the [[when installing from live][Intel Wireless Wi-Fi Drivers]] after the installation.

** TODO: Uncategorized
*** Can't access Cinnamon settings

You have to downgrade the PIL to 5.4.1
*** Weather info not displaying in the homepage

Set mixed content to false in about:config

*** What's the command for rofi?

=rofi -show drun=

*** Get rid of Gnome-Terminal titlebar?

run
=gsettings set org.gnome.Terminal.Legacy.Settings headerbar "@mb false"=

*** Gnome-Terminal doesn't recognized installed Nerd Font

Use Gnome-Tweak-Tools and change the monospace font globally

*** [[https://www.linuxmint.com/searchengines.php][Set Google as default search engine in Linux Mint?]]

*** Red error indication in powerline every time I open terminal

Probably because I didn't install fzf or node or something else

*** Change screenshot to show more options

Set shortcut to =/usr/bin/gnome-screenshot --interactive=

*** Go Autocomplete in YouCompleteMe

Run =./.vim/plugged/YouCompleteMe/install.py --go-completer=

*** Applications not showing up in rofi

Add .desktop files to ~/.local/share/applications

*** Icons for rofi?

=~/.icons=

*** Connect to WiFi with redirect page.

[[https://unix.stackexchange.com/questions/89630/how-to-sign-into-an-open-wireless-network][Try 192.168.1.1]]

*** Prettier not working / npm not found

Turn on node, =nvm use node=

*** Wifi not detected on fresh install

[[https://askubuntu.com/questions/730799/installing-firmware-b43-installer-offline][Copy b43 onto a flashdrive]]

*** Slow WiFi on iMac

[[https://archived.forum.manjaro.org/t/solved-bcm4331-inconsistent-and-slow-wifi-on-mac/95386/2][Install drivers]]

*** SSH not working in rofi?

[[https://linuxize.com/post/using-the-ssh-config-file/][Add ~/.ssh/config file]]

*** [[https://linux-tips.com/t/how-to-fix-apple-imac-headphone-sound-problem/285][No sound from iMac headphone jack]]

Add =options snd-hda-intel model=imac27_122= to =/etc/modprobe.d/sound.conf=

*** Connect to wifi automatically (wpa_supplicant)

#+BEGIN_EXAMPLE
  https://www.linuxbabe.com/command-line/ubuntu-server-16-04-wifi-wpa-supplicant
#+END_EXAMPLE

*** Automatic updates on Ubuntu

#+BEGIN_EXAMPLE
  1. apt install unattended-upgrades
  2. dpkg-reconfigure --priority=low unattended-upgrades
#+END_EXAMPLE

*** Ctrl-G for fzf?

**** Bash

#+BEGIN_SRC sh
  bind '"\C-t": transpose-chars'
  bind -x '"\C-g": fzf-file-widget'
#+END_SRC

**** ZSH

#+BEGIN_EXAMPLE
  bindkey '^G' fzf-file-widget
  bindkey '^T' transpose-chars
#+END_EXAMPLE

*** No emojis on Arch?

Install =extra/noto-fonts-emoji=

*** SSH permission denied?

Probably an issue on my end.

#+BEGIN_EXAMPLE
  # /etc/ssh/ssh_config
  PasswordAuthentication yes
#+END_EXAMPLE

*** rsync into mobile?

#+BEGIN_EXAMPLE
  rsync -e 'ssh -p 8022' <FILES> u0_a500@192.168.1.XXX:/data/data/com.termux/files/home/storage/
#+END_EXAMPLE

*** Set folding in files

Add this to the bottom of the file

#+BEGIN_EXAMPLE
  # vim: foldmethod=marker:foldlevel=0
#+END_EXAMPLE

*** Trouble converting images to PDF with ImageMagick

[[https://stackoverflow.com/questions/31407010/cache-resources-exhausted-imagemagick][Cache exhausted]]

#+BEGIN_EXAMPLE
  # /etc/ImageMagick-6/policy.xml
  <policy domain="resource" name="disk" value="8GiB"/>
  <policy domain="resource" name="area" value="1GiB"/>
#+END_EXAMPLE

[[https://stackoverflow.com/questions/52998331/imagemagick-security-policy-pdf-blocking-conversion][PDF blocked security policy]]

#+BEGIN_EXAMPLE
  # /etc/ImageMagick-6/policy.xml
  ...
  <policy domain="coder" rights="read | write" pattern="PDF" />
  ...
  </policymap>
#+END_EXAMPLE

*** Bluetooth =org.bluez.Error.Failed=

[[https://unix.stackexchange.com/questions/258074/error-when-trying-to-connect-to-bluetooth-speaker-org-bluez-error-failed][Possibly missing packages]]

#+BEGIN_EXAMPLE
  sudo apt install pulseaudio-module-bluetooth
  pulseaudio -k
  pulseaudio --start
#+END_EXAMPLE

*** Bluetooth =Failed to pair: org.bluez.Error.AlreadyExists=

Try restarting bluetooth

#+BEGIN_EXAMPLE
  sudo service bluetooth restart
#+END_EXAMPLE

Or maybe [[https://stackoverflow.com/questions/54387985/bluetooth-blocked-through-rfkill][rfkill is blocking bluetooth]]

#+BEGIN_EXAMPLE
  # check status
  sudo service bluetooth status
  sudo rfkill unblock bluetooth
#+END_EXAMPLE

*** Bluetooth
[[https://askubuntu.com/questions/1172000/a2dp-sink-profile-connect-failed][a2dp-sink profile connect failed. Protocol not available]]

#+BEGIN_EXAMPLE
  sudo apt-get install pulseaudio-module-bluetooth
  sudo killall pulseaudio
  pulseaudio --start
  sudo service bluetooth restart
#+END_EXAMPLE

*** [[https://gist.github.com/oanhnn/80a89405ab9023894df7][Multiple Github Accounts Using SSH]]

#+BEGIN_EXAMPLE
  # Account 1
  Host github-1
     HostName github.com
     IdentityFile ~/.ssh/key_1
     IdentitiesOnly yes

  # Account 2
  Host github-2
     HostName github.com
     IdentityFile ~/.ssh/key_2
     IdentitiesOnly yes
#+END_EXAMPLE

*** [[https://stackoverflow.com/questions/5166652/how-to-view-utf-8-characters-in-vim-or-gvim][Render Japanese UTF8 in Vim]]

.vimrc

#+BEGIN_EXAMPLE
      set encoding=utf-8
      set fileencodings=iso-2022-jp,euc-jp,sjis,utf-8
      set fileformats=unix,dos,mac
#+END_EXAMPLE

*** [[https://gitlab.gnome.org/GNOME/evince/-/issues/925][Open CBZ containing WEBP with evince]]

[[https://github.com/aruiz/webp-pixbuf-loader/][Install webp-pixbuf-loader]]

*** [[https://askubuntu.com/questions/1404353/how-to-install-qt6-on-ubuntu-21-10][Install Anki on Ubuntu]]

#+BEGIN_EXAMPLE
  sudo apt install qt6-base-dev
  sudo apt install libxcb-cursor0
#+END_EXAMPLE

*** Sound not working on Galaxy Book

[[https://github.com/joshuagrisham/galaxy-book2-pro-linux][necessary-verbs.sh]]

*** [[https://devtoolstips.org/tips/en/disable-abusive-debugger-statement/][Website stuck on debugger while using Inspect Element]]

set debugger
=Conditional breakpoint=
to
=false=

*** rofi application not changing after editing .desktop file

For snaps check =/var/lib/snapd/desktop/applications=

*** Don't count underscores (_) as part of a word in Vim

=:set iskeyword-=_=

*** Source virtualenv from bash script

[[https://stackoverflow.com/a/13122219][Source from .bashrc instead]]

#+BEGIN_SRC sh
  activate () {
    . ../.env/bin/activate
  }
#+END_SRC

*** [[https://unix.stackexchange.com/a/676973][Failed to connect: org.bluez.Error.NotReady br-connection-adapter-not-powered]]

#+BEGIN_EXAMPLE
  /etc/bluetooth/main.conf
#+END_EXAMPLE

#+BEGIN_EXAMPLE
  [Policy]
  # ... snip ...
  AutoEnable=true
#+END_EXAMPLE

*** Ctrl + Backspace

[[https://www.reddit.com/r/neovim/comments/prp8zw/comment/hdkdd7a/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button][vim]]

#+BEGIN_EXAMPLE
  imap <C-H> <C-W>
#+END_EXAMPLE

[[https://unix.stackexchange.com/a/264871][bash]]

#+BEGIN_EXAMPLE
  ~/.inputrc
#+END_EXAMPLE

#+BEGIN_EXAMPLE
  "\C-h": backward-kill-word
  "\e[3;5~": kill-word
#+END_EXAMPLE

*** [[https://github.com/keepassxreboot/keepassxc/issues/1267][KeepassXC Unlock on Login]]

#+BEGIN_EXAMPLE
  # store a new password:
  secret-tool store --label='Keepass' database pass.xdbx

  # query and start keepassxc:
  secret-tool lookup database pass.xdbx | keepassxc --pw-stdin ~/pass.xdbx
#+END_EXAMPLE

*** [[https://askubuntu.com/a/1035917][Remove snap from Ubuntu]]

#+BEGIN_EXAMPLE
  sudo apt autoremove --purge snapd
  sudo apt-mark hold snapd

  # or [this answer](https://askubuntu.com/questions/1345385/how-can-i-stop-apt-from-installing-snap-packages/1345401#1345401)

  cat <<EOF | sudo tee /etc/apt/preferences.d/nosnap.pref
  # To prevent repository packages from triggering the installation of Snap,
  # this file forbids snapd from being installed by APT.
  # For more information: https://linuxmint-user-guide.readthedocs.io/en/latest/snap.html

  Package: snapd
  Pin: release a=*
  Pin-Priority: -10
  EOF
#+END_EXAMPLE

*** [[https://vim.fandom.com/wiki/Fix_meta-keys_that_break_out_of_Insert_mode][Remap Alt in Vim]]

#+BEGIN_EXAMPLE
  :set <M-A>=<press Ctrl-V><press Meta-A>
  :imap <press Ctrl-v><press Esc>a <M-A>
#+END_EXAMPLE

*** [[https://unix.stackexchange.com/questions/298492/make-mpv-display-name-of-youtube-link-when-playing-just-audio][Display title in mpv playing youtube video]]

#+BEGIN_EXAMPLE
  mpv --term-playing-msg='${media-title}' <URL>
#+END_EXAMPLE

*** [[https://wiki.linuxquestions.org/wiki/List_of_Keysyms_Recognised_by_Xmodmap][xmodmap Key Names]]
*** [[https://forums.ankiweb.net/t/airpods-audio-is-delayed/35712/2][Anki: Sound playback delay]]
Play silence in the background to keep audio device active.

**** [[https://stackoverflow.com/a/16715419][Generate silent mp3 from ffmpeg]]
#+begin_example shell
ffmpeg -f lavfi -i anullsrc=r=44100:cl=mono -t <SECONDS> -q:a 9 -acodec libmp3lame out.mp3
#+end_example
