#!/bin/bash
# 2install - installs and configure machine automatically (Ubuntu)

# PPA
    # Papirus
        sudo add-apt-repository ppa:papirus/papirus

    # OBS
        sudo add-apt-repository ppa:obsproject/obs-studio

    # Brave
        sudo apt install apt-transport-https curl

        sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

        echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list

# Update system
    yes | sudo apt update
    yes | sudo apt upgrade

# Programming

    # Python
        yes | sudo apt install python3
        yes | sudo apt install python3-pip
        pip3 install --upgrade setuptools

    # Golang
        wget "https://golang.org/dl/go1.15.3.linux-amd64.tar.gz"
        sudo tar -C /usr/local -xzf go1.*15*.3.linux-amd64.tar.gz
        export PATH="$PATH:/usr/local/go/bin"
        export GOPATH="$HOME/Code/Go"
        export PATH="$PATH:$GOPATH/bin"
        export GOBIN="$GOPATH/bin"

    # Rust
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
        export PATH="$PATH:$HOME/.cargo/bin"

    # node-version-manager
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

# Firefox Addons
    cd ..
    go run firefox.go & sleep 1 && firefox localhost:3000 &
    cd -

# Brave
    sudo apt install brave-browser

# Theming

    # GTK
        yes | sudo apt install arc-theme

    # Icons
        yes | sudo apt-get install papirus-icon-theme

    # Fonts
        wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
        wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf

        mv PowerlineSymbols.otf ~/.local/share/fonts/
        sudo fc-cache -vf ~/.local/share/fonts/
        mkdir -p /home/ddmin/.config/fontconfig
        mv 10-powerline-symbols.conf /home/ddmin/.config/fontconfig/conf.d

        # Microsoft Fonts
        # yes | sudo apt install ttf-mscorefonts-installer

# Dependencies
    yes | sudo apt install python3-dev
    yes | sudo apt install libjpeg-dev
    yes | sudo apt install zlib1g-dev
    yes | sudo apt install libxtst-dev
    yes | sudo apt install cmake
    yes | sudo apt install build-essential
    yes | sudo apt-get install dconf-cli uuid-runtime

# Install vim
    yes | sudo apt install vim
    yes | sudo apt install neovim

# Install system tools
    yes | sudo apt install zsh
    yes | sudo apt install git
    yes | sudo apt install openssh-server
    yes | sudo apt install curl
    yes | sudo apt install wget
    yes | sudo apt install lynx
    yes | sudo apt install xsel
    yes | sudo apt install xdotool

# Install utilities

    # rofi
        yes | sudo apt install rofi

    # neofetch
        yes | sudo apt install neofetch

    # ranger
        yes | sudo apt install ranger
        ranger --copy-config=all

        # devicons
        git clone https://github.com/ddmin/ranger_devicons.git /tmp/devicons
        cd /tmp/devicons
        make install
        cd -

    # fzf
        git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
        yes | ~/.fzf/install

    # logo-ls
        go get github.com/ddmin/logo-ls

    # powerline-go
        go get -u github.com/justjanne/powerline-go

    # ripgrep
        cargo install ripgrep

    # exa
        cargo install exa

# Graphics
    pip3 install ueberzug
    pip3 install pywal
    yes | sudo apt install gimp
    yes | sudo apt install feh
    yes | sudo apt install imagemagick

# Media
    yes | sudo apt install obs-studio
    yes | sudo apt install mpv
    yes | sudo apt install vlc
    yes | sudo apt install ffmpegthumbnailer
    yes | sudo apt install cmus
    yes | sudo apt install id3v2
    yes | sudo apt install lame

# Documents
    yes | sudo apt install texlive-full
    yes | sudo apt install texlive-xetex
    yes | sudo apt install pandoc
    yes | sudo apt install zathura

echo 'Setup Complete'
echo 'Please reboot your machine.'
