#!/bin/bash
# 2install - installs and configure machine automatically (Ubuntu)

# Variables
    export PATH="$PATH:/usr/local/go/bin"
    export PATH="$PATH:$GOPATH/bin"
    export PATH="$PATH:$HOME/.cargo/bin"

    export GO_VERSION="go1.17.3"
    export GOPATH="$HOME/Code/Go"
    export GOBIN="$GOPATH/bin"
    export GO_SRC="$GOPATH/src/github.com/ddmin"

    export NVM_DIR="$HOME/.nvm"

# Directories
    mkdir -p $HOME/.local/bin/
    mkdir -p $HOME/.local/share/fonts
    mkdir -p $HOME/.config/fontconfig

# PPA
    # Papirus
        sudo add-apt-repository ppa:papirus/papirus

    # OBS
        sudo add-apt-repository ppa:obsproject/obs-studio

    # Brave
        yes | sudo apt install apt-transport-https curl

        sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

        echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list

# Update system
    yes | sudo apt update
    yes | sudo apt upgrade

# Programming

    # Python
        yes | sudo apt install python3
        yes | sudo apt install python3-pip
        pip3 install --upgrade setuptools

    # Golang
        wget "https://golang.org/dl/$GO_VERSION.linux-amd64.tar.gz"
        sudo tar -C /usr/local -xzf go*linux-amd64.tar.gz

    # Rust
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

    # Node
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Firefox Addons
    cd ..
    go run firefox.go & sleep 1 && firefox 127.0.0.1:3000 &
    cd -

# Brave
    yes | sudo apt install brave-browser

# Kitty Terminal
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
    ln -s $HOME/.local/kitty.app/bin/kitty $HOME/.local/bin/
    cp $HOME/.local/kitty.app/share/applications/kitty.desktop $HOME/.local/share/applications/
    sed -i "s|Icon=kitty|Icon=/home/$USER/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" $HOME/.local/share/applications/kitty.desktop

# Theming

    # GTK
        yes | sudo apt install arc-theme

    # Icons
        yes | sudo apt-get install papirus-icon-theme

    # Fonts
        wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
        wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf

        mv PowerlineSymbols.otf $HOME/.local/share/fonts/
        mv 10-powerline-symbols.conf "$HOME/.config/fontconfig/conf.d"

        # SauceCodePro
        mv "../ASSETS/Sauce Code Pro Nerd Font Complete Mono.ttf" $HOME/.local/share/fonts/
        sudo fc-cache -vf $HOME/.local/share/fonts/

# Dependencies
    yes | sudo apt install build-essential
    yes | sudo apt install cmake
    yes | sudo apt install dconf-cli
    yes | sudo apt install libjpeg-dev
    yes | sudo apt install libssl-dev
    yes | sudo apt install libxtst-dev
    yes | sudo apt install pkg-config
    yes | sudo apt install python3-dev
    yes | sudo apt install uuid-runtime
    yes | sudo apt install zlib1g-dev

# Install vim
    yes | sudo apt install vim

# Install neovim
    yes | sudo apt install neovim
    wget https://github.com/neovim/neovim/releases/download/v0.5.1/nvim.appimage
    chmod u+x nvim.appimage
    sudo mv nvim.appimage /usr/bin/nvim

# Install zsh
    yes | sudo apt install zsh

    # syntax highlighting
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.zsh/zsh-syntax-highlighting

    # tab title
    git clone https://github.com/ddmin/zsh-tab-title.git $HOME/.zsh/zsh-tab-title

# Install system tools
    yes | sudo apt install bluez
    yes | sudo apt install curl
    yes | sudo apt install dialog
    yes | sudo apt install git
    yes | sudo apt install openssh-server
    yes | sudo apt install rsync
    yes | sudo apt install tlp
    yes | sudo apt install wget
    yes | sudo apt install xdotool
    yes | sudo apt install xsel

# Install utilities
    yes | sudo apt install rofi
    yes | sudo apt install neofetch

    yes | sudo apt install ranger
    ranger --copy-config=all

    # devicons
    git clone https://github.com/ddmin/ranger_devicons.git /tmp/devicons
    cd /tmp/devicons
    make install
    cd -

    # syntax highlighting
    yes | sudo apt install highlight

# Golang
    # fzf
    git clone --depth 1 https://github.com/junegunn/fzf.git $HOME/.fzf
    yes | $HOME/.fzf/install

    # powerline-go
    go get -u github.com/justjanne/powerline-go

    # lazygit
    go get github.com/jesseduffield/lazygit

    # logo-ls
    mkdir -p "$GO_SRC/logo-ls"
    git clone https://github.com/ddmin/logo-ls "$GO_SRC/logo-ls"

    cd "$GO_SRC/logo-ls"
    go build
    go install
    cd -

# Rust
    cargo install bat
    cargo install ripgrep
    cargo install exa
    cargo install fd-find

    # cargo extensions
    cargo install cargo-edit
    cargo install cargo-watch

# Graphics
    pip3 install ueberzug
    yes | sudo apt install feh
    yes | sudo apt install gimp
    yes | sudo apt install imagemagick
    yes | sudo apt install w3m-img

# Media
    yes | sudo apt install ffmpeg
    yes | sudo apt install ffmpegthumbnailer
    yes | sudo apt install mpd
    yes | sudo apt install mpv
    yes | sudo apt install ncmpcpp
    yes | sudo apt install obs-studio
    yes | sudo apt install vlc

# Documents
    yes | sudo apt install pandoc
    yes | sudo apt install zathura
    yes | sudo apt install zathura-pdf-poppler

# LaTeX
    yes | sudo apt install texlive-full
    yes | sudo apt install texlive-xetex

# Wireguard
    yes | sudo apt install wireguard

sudo chsh -s $(which zsh) "$USER"

echo 'Setup Complete'
echo 'Please reboot your machine.'
