#!/bin/bash
# install - installs and configure machine automatically (Ubuntu)

# Update system
    yes | sudo apt update
    yes | sudo apt upgrade

# Install git
    yes | sudo apt install git

# Install fzf
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    yes | ~/.fzf/install

# Install curl
    yes | sudo apt install curl

# Install vim
    yes | sudo apt install vim

# Install ranger
    git clone https://github.com/ranger/ranger.git /tmp/ranger
    cd /tmp/ranger
    sudo make install

# Install ranger devicons
    git clone https://github.com/alexanderjeurissen/ranger_devicons.git /tmp/devicons
    cd /tmp/devicons
    make install

# Return to home directory
    cd

# Copy ranger configs
    ranger --copy-config=all

# Install cmus
    yes | sudo apt install cmus

# Install git
    yes | sudo apt install git

# Install neofetch
    yes | sudo apt install neofetch

# Install rofi
    # Command to run rofi: rofi -modi drun -show drun -show-icons
    yes | sudo apt install rofi

# Install python and pip
    yes | sudo apt install python
    yes | sudo apt install python-pip
    sudo -H pip install --upgrade setuptools

# Install python3 and pip3
    yes | sudo apt install python3
    yes | sudo apt install python3-pip
    sudo -H pip3 install --upgrade setuptools

# Install powerline-shell
    sudo -H pip install powerline-shell

# Dependencies
    yes | sudo apt install python3-dev
    yes | sudo apt install libjpeg-dev
    yes | sudo apt install zlib1g-dev
    yes | sudo apt install libxtst-dev

# Install ueberzug
    sudo pip3 install ueberzug

# Install mpv
    yes | sudo apt install mpv

# Install vlc
    yes | sudo apt install vlc

# Install feh
    yes | sudo apt install feh

# Install pywal
    sudo -H pip3 install pywal

# Install imagemagick
    yes | sudo apt install imagemagick

# Install calcurse
    yes | sudo apt install calcurse

# Install zathura
    yes | sudo apt install zathura

# Install id3v2
    yes | sudo apt install id3v2

# Install lsd
    wget https://github.com/Peltoche/lsd/releases/download/0.16.0/lsd_0.16.0_amd64.deb

    sudo dpkg -i lsd_0.16.0_amd64.deb

    # Remove deb file
    rm lsd_0.16.0_amd64.deb

# Install SauceCodePro
    wget https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/SourceCodePro/Semibold/complete/Sauce%20Code%20Pro%20Semibold%20Nerd%20Font%20Complete%20Mono.ttf
    sudo mv Sauce Code Pro Semibold Nerd Font Complete Mono.ttf /usr/share/fonts

# Install and configure sdcv
    yes | sudo apt install wget
    yes | sudo apt install sdcv

    wget https://web.archive.org/web/20140428003644/http://abloz.com/huzheng/stardict-dic/dict.org/stardict-dictd_www.dict.org_gcide-2.4.2.tar.bz2

    sudo mkdir -p /usr/share/stardict/dic/

    sudo tar -xvjf  stardict-dictd_www.dict.org_gcide-2.4.2.tar.bz2 -C /usr/share/stardict/dic

    rm stardict-dictd_www.dict.org_gcide-2.4.2.tar.bz2

# Dotfiles
    cd /tmp
    git clone https://github.com/ddmin/Dotfiles.git
    cd Dotfiles
    cd dotfiles
    ./setup.sh
