#!/bin/bash
# install python2.7

# install python2
    yes | sudo apt install python
    yes | sudo apt install python2
    curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py
    sudo python2 get-pip.py
