#!/bin/bash
# 2install - installs and configure machine automatically (Ubuntu)

sudo echo "Installing ranger..."

cd ..
sudo mv ./ranger/ranger /usr/local/bin
sudo mv -v ./ranger/* /usr/lib/python2.7

sudo echo "Finished."
