#!/bin/bash
# 3install -  minimal configurations to a fresh Arch install

# update system
    sudo pacman -Syyu

# dependencies
    sudo pacman -S base-devel
    sudo pacman -S curl
    sudo pacman -S xz
    sudo pacman -S git
    sudo pacman -S python

# fonts
    sudo pacman -S noto-fonts

# picom
    sudo pacman -S picom

# yay
    git clone https://aur.archlinux.org/yay.git /tmp/yay
    cd /tmp/yay
    makepkg -si
    cd -

# utilities
    sudo pacman -S vim
    sudo pacman -S ranger

# graphical environment
    sudo pacman -S xorg-server xorg-xinit xterm
    cp /etc/X11/xinit/xinitrc ~/.xinitrc
    echo "exec i3" >> ~/.xinitrc

    pip3 install i3ipc

    sudo pacman -S lightdm lightdm-gtk-greeter
    sudo systemctl enable lightdm

    sudo pacman -S i3-gaps i3-status
    sudo pacman -S rxvt-unicode dmenu rofi

echo 'Setup Complete'
echo 'Please reboot your machine.'
