#!/bin/bash
# 3install -  minimal configurations to a fresh Arch install

# update system
    sudo pacman -Syyu

# dependencies
    sudo pacman -S base-devel curl wget xz uthash git
    sudo pacman -S python python-pip

# fonts
    sudo pacman -S noto-fonts

# wallpaper
    sudo pacman -S nitrogen picom

# utilities
    sudo pacman -S vim ranger htop scrot rxvt-unicode dmenu

# graphical environment
    sudo pacman -S xorg-server xorg-xinit xorg-xrandr xorg-xbacklight xterm
    cp /etc/X11/xinit/xinitrc ~/.xinitrc
    echo "exec i3" >> ~/.xinitrc

    sudo pacman -S sddm
    sudo systemctl enable sddm

    sudo pacman -S i3-gaps i3status i3lock
    pip install i3ipc

# yay
    git clone https://aur.archlinux.org/yay.git /tmp/yay
    cd /tmp/yay
    makepkg -si
    cd -

# alttab
    git clone https://github.com/sagb/alttab.git /tmp/alttab
    cd /tmp/alttab
    ./configure && sudo make install
    cd -

# iosevka nerd font
    yay -S ttf-iosevka-nerd

echo 'Setup Complete'
echo 'Please reboot your machine.'
