#!/bin/bash
# i3-install - installs and configures i3 machine

# Install flashfocus
    yes | sudo apt-get install libxcb-render0-dev libffi-dev python-dev python-cffi
    pip install flashfocus

# polybar
# from regolith-speed-ricer
    sudo add-apt-repository -y ppa:kgilmer/speed-ricer
    yes | sudo apt install polybar
